### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by DerNoobikeks** [mclarence01/Account-Checker#1]
What about an option that checks the country of the spotify account?

**Comment by mclarence01** [comment]
May I ask why this is needed? Im pretty sure country doesnt make a difference with a spotify account.

**Comment by DerNoobikeks** [comment]
Some songs are region locked.

**Comment by mclarence01** [comment]
Ok, will add.

**Comment by DerNoobikeks** [comment]
Thanks!

**Comment by mclarence01** [comment]
d5811850036a82a8c2fe2b8044b4fc47bdd369e7

**Comment by mclarence01** [comment]
https://github.com/mclarence01/Account-Checker/releases/tag/v2.0.2
